### ISSUE TITLE
tweeting (video) on behalf of a user

### ISSUE THREAD

**Issue by pietrop** [janzal/twitter-media#1]
I am working on an app, where the user signs in with passportjs twitter authentication (and therefore providing individual user `token` and `token_secret`) and then the application tweets a video on his/hers behalf.

However using `twitter-media` I get the following error:

```
TypeError: Cannot read property 'media_id_string' of undefined
```

it does however work when  `token` and `token_secret` are the same registered with the application.

Any ideas on what might be the problem?

**Comment by janzal** [comment]
Hi,
Currently I am not sure what's the issue. I'll check it out ;)

**Comment by janzal** [comment]
I cannot reproduce your issue. It occurs when there is empty body in response. It might be something with video format. It currently handles only video/mp4 imo.

**Comment by janzal** [comment]
I've checked your project InteractiveVideoComponents and it seems to me, that video is refused by Twitter because of breaking their recommendations for uploaded videos. 

https://dev.twitter.com/rest/public/uploading-media#videorecs

**Comment by janzal** [comment]
I've checked your project InteractiveVideoComponents and it seems to me, that video is refused by Twitter because of possible breaking their recommendations for uploaded videos. Didn't you exceeded 15MB?

https://dev.twitter.com/rest/public/uploading-media#videorecs

**Comment by pietrop** [comment]
Thanks for looking into it.
Yes, I am abstracting the components int the [interactive video components repo](https://github.com/pietrop/InteractiveVideoComponents) for reusability.
However the main project is [quickQuote](https://github.com/pietrop/quickQuoteNode) which is a refactor in node of the ruby on rails [times.github.io/quickQuote](http://times.github.io/quickQuote/).

I wrote a module to [trim the video](https://github.com/pietrop/InteractiveVideoComponents/blob/master/interactive_video_components/export/twitter_video/trim_video.js) as part of [a group of modules to deal with the twitter video API](https://github.com/pietrop/InteractiveVideoComponents/tree/master/interactive_video_components/export/twitter_video)

the [`upload_twitter_video`](https://github.com/pietrop/InteractiveVideoComponents/blob/master/interactive_video_components/export/twitter_video/upload_twitter_video.js) one uses `Twit` and  `twitter-media` to do what it says on the tin.

and the [`trim_video_and_upload_to_twitter`](https://github.com/pietrop/InteractiveVideoComponents/blob/master/interactive_video_components/export/twitter_video/trim_video_and_upload_to_twitter.js) combines the two.

I think in the [`trim_video`](https://github.com/pietrop/InteractiveVideoComponents/blob/master/interactive_video_components/export/twitter_video/trim_video.js)  I got most of the specs right, as I followed the [twitter video specs](https://dev.twitter.com/rest/public/uploading-media#videorecs) and it works, but I couldn't find a way to restrict the file size of the video using `fluent-ffmpeg`.

Anyway back to the original issue, I think it was to do with the newly created twitter account, as tried with a different account and tweeting on behalf of a user( as in using different `token` and `token_secret` of the application once) it worked. so I am happy for this to be marked as resolved.
